### YamlMime:ManagedReference
items:
- uid: RGBLineCoreLib.Data.GameConfigData
  commentId: T:RGBLineCoreLib.Data.GameConfigData
  id: GameConfigData
  parent: RGBLineCoreLib.Data
  children:
  - RGBLineCoreLib.Data.GameConfigData.MaxFrame
  - RGBLineCoreLib.Data.GameConfigData.MusicVolume
  - RGBLineCoreLib.Data.GameConfigData.NoteHitJudgeStrandard
  - RGBLineCoreLib.Data.GameConfigData.VSyncCount
  langs:
  - csharp
  - vb
  name: GameConfigData
  nameWithType: GameConfigData
  fullName: RGBLineCoreLib.Data.GameConfigData
  type: Struct
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: GameConfigData
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 9
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  syntax:
    content: public struct GameConfigData
    content.vb: Public Structure GameConfigData
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetType
- uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgeStrandard
  commentId: F:RGBLineCoreLib.Data.GameConfigData.NoteHitJudgeStrandard
  id: NoteHitJudgeStrandard
  parent: RGBLineCoreLib.Data.GameConfigData
  langs:
  - csharp
  - vb
  name: NoteHitJudgeStrandard
  nameWithType: GameConfigData.NoteHitJudgeStrandard
  fullName: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgeStrandard
  type: Field
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: NoteHitJudgeStrandard
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 39
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  syntax:
    content: public GameConfigData.NoteHitJudgingStrandard NoteHitJudgeStrandard
    return:
      type: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard
    content.vb: Public NoteHitJudgeStrandard As GameConfigData.NoteHitJudgingStrandard
- uid: RGBLineCoreLib.Data.GameConfigData.MusicVolume
  commentId: F:RGBLineCoreLib.Data.GameConfigData.MusicVolume
  id: MusicVolume
  parent: RGBLineCoreLib.Data.GameConfigData
  langs:
  - csharp
  - vb
  name: MusicVolume
  nameWithType: GameConfigData.MusicVolume
  fullName: RGBLineCoreLib.Data.GameConfigData.MusicVolume
  type: Field
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: MusicVolume
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 47
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  summary: 게임 전체 볼륨을 조절한다
  remarks: 0.0f ~ 1.0f 사이의 값으로 지정한다
  example: []
  syntax:
    content: public float MusicVolume
    return:
      type: System.Single
    content.vb: Public MusicVolume As Single
- uid: RGBLineCoreLib.Data.GameConfigData.MaxFrame
  commentId: F:RGBLineCoreLib.Data.GameConfigData.MaxFrame
  id: MaxFrame
  parent: RGBLineCoreLib.Data.GameConfigData
  langs:
  - csharp
  - vb
  name: MaxFrame
  nameWithType: GameConfigData.MaxFrame
  fullName: RGBLineCoreLib.Data.GameConfigData.MaxFrame
  type: Field
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: MaxFrame
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 48
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  syntax:
    content: public GameConfigData.MaxFrameRate MaxFrame
    return:
      type: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
    content.vb: Public MaxFrame As GameConfigData.MaxFrameRate
- uid: RGBLineCoreLib.Data.GameConfigData.VSyncCount
  commentId: F:RGBLineCoreLib.Data.GameConfigData.VSyncCount
  id: VSyncCount
  parent: RGBLineCoreLib.Data.GameConfigData
  langs:
  - csharp
  - vb
  name: VSyncCount
  nameWithType: GameConfigData.VSyncCount
  fullName: RGBLineCoreLib.Data.GameConfigData.VSyncCount
  type: Field
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: VSyncCount
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 55
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  summary: 게임의 V Sync 수준을 조절한다
  remarks: 0 ~ 4 사이의 값으로 지정한다
  example: []
  syntax:
    content: public int VSyncCount
    return:
      type: System.Int32
    content.vb: Public VSyncCount As Integer
references:
- uid: RGBLineCoreLib.Data
  commentId: N:RGBLineCoreLib.Data
  href: RGBLineCoreLib.html
  name: RGBLineCoreLib.Data
  nameWithType: RGBLineCoreLib.Data
  fullName: RGBLineCoreLib.Data
  spec.csharp:
  - uid: RGBLineCoreLib
    name: RGBLineCoreLib
    href: RGBLineCoreLib.html
  - name: .
  - uid: RGBLineCoreLib.Data
    name: Data
    href: RGBLineCoreLib.Data.html
  spec.vb:
  - uid: RGBLineCoreLib
    name: RGBLineCoreLib
    href: RGBLineCoreLib.html
  - name: .
  - uid: RGBLineCoreLib.Data
    name: Data
    href: RGBLineCoreLib.Data.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard
  commentId: T:RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard
  parent: RGBLineCoreLib.Data
  href: RGBLineCoreLib.Data.GameConfigData.html
  name: GameConfigData.NoteHitJudgingStrandard
  nameWithType: GameConfigData.NoteHitJudgingStrandard
  fullName: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard
  spec.csharp:
  - uid: RGBLineCoreLib.Data.GameConfigData
    name: GameConfigData
    href: RGBLineCoreLib.Data.GameConfigData.html
  - name: .
  - uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard
    name: NoteHitJudgingStrandard
    href: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.html
  spec.vb:
  - uid: RGBLineCoreLib.Data.GameConfigData
    name: GameConfigData
    href: RGBLineCoreLib.Data.GameConfigData.html
  - name: .
  - uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard
    name: NoteHitJudgingStrandard
    href: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.html
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  commentId: T:RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  parent: RGBLineCoreLib.Data
  href: RGBLineCoreLib.Data.GameConfigData.html
  name: GameConfigData.MaxFrameRate
  nameWithType: GameConfigData.MaxFrameRate
  fullName: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  spec.csharp:
  - uid: RGBLineCoreLib.Data.GameConfigData
    name: GameConfigData
    href: RGBLineCoreLib.Data.GameConfigData.html
  - name: .
  - uid: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
    name: MaxFrameRate
    href: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.html
  spec.vb:
  - uid: RGBLineCoreLib.Data.GameConfigData
    name: GameConfigData
    href: RGBLineCoreLib.Data.GameConfigData.html
  - name: .
  - uid: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
    name: MaxFrameRate
    href: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.html
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
