### YamlMime:ManagedReference
items:
- uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  commentId: T:RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  id: GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  parent: RGBLineCoreLib.Data
  children:
  - RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Good
  - RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Miss
  - RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Perfect
  langs:
  - csharp
  - vb
  name: GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  nameWithType: GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  fullName: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  type: Enum
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: HitJudgingType
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 29
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  syntax:
    content: public enum GameConfigData.NoteHitJudgingStrandard.HitJudgingType
    content.vb: Public Enum GameConfigData.NoteHitJudgingStrandard.HitJudgingType
- uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Perfect
  commentId: F:RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Perfect
  id: Perfect
  parent: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  langs:
  - csharp
  - vb
  name: Perfect
  nameWithType: GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Perfect
  fullName: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Perfect
  type: Field
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: Perfect
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 31
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  syntax:
    content: Perfect = 0
    return:
      type: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
- uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Good
  commentId: F:RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Good
  id: Good
  parent: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  langs:
  - csharp
  - vb
  name: Good
  nameWithType: GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Good
  fullName: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Good
  type: Field
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: Good
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 32
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  syntax:
    content: Good = 1
    return:
      type: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
- uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Miss
  commentId: F:RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Miss
  id: Miss
  parent: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  langs:
  - csharp
  - vb
  name: Miss
  nameWithType: GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Miss
  fullName: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.Miss
  type: Field
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: Miss
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 33
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  syntax:
    content: Miss = 2
    return:
      type: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
references:
- uid: RGBLineCoreLib.Data
  commentId: N:RGBLineCoreLib.Data
  href: RGBLineCoreLib.html
  name: RGBLineCoreLib.Data
  nameWithType: RGBLineCoreLib.Data
  fullName: RGBLineCoreLib.Data
  spec.csharp:
  - uid: RGBLineCoreLib
    name: RGBLineCoreLib
    href: RGBLineCoreLib.html
  - name: .
  - uid: RGBLineCoreLib.Data
    name: Data
    href: RGBLineCoreLib.Data.html
  spec.vb:
  - uid: RGBLineCoreLib
    name: RGBLineCoreLib
    href: RGBLineCoreLib.html
  - name: .
  - uid: RGBLineCoreLib.Data
    name: Data
    href: RGBLineCoreLib.Data.html
- uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  commentId: T:RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  parent: RGBLineCoreLib.Data
  href: RGBLineCoreLib.Data.GameConfigData.html
  name: GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  nameWithType: GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  fullName: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
  spec.csharp:
  - uid: RGBLineCoreLib.Data.GameConfigData
    name: GameConfigData
    href: RGBLineCoreLib.Data.GameConfigData.html
  - name: .
  - uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard
    name: NoteHitJudgingStrandard
    href: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.html
  - name: .
  - uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
    name: HitJudgingType
    href: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.html
  spec.vb:
  - uid: RGBLineCoreLib.Data.GameConfigData
    name: GameConfigData
    href: RGBLineCoreLib.Data.GameConfigData.html
  - name: .
  - uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard
    name: NoteHitJudgingStrandard
    href: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.html
  - name: .
  - uid: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType
    name: HitJudgingType
    href: RGBLineCoreLib.Data.GameConfigData.NoteHitJudgingStrandard.HitJudgingType.html
