### YamlMime:ManagedReference
items:
- uid: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface
  commentId: T:RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface
  id: StageDataInterface.StageConfigDataInterface
  parent: RGBLineCoreLib.Functor
  children:
  - RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.GetStageConfigData
  - RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.SetStageConfigData(RGBLineCoreLib.Data.StageData.StageConfigData@)
  langs:
  - csharp
  - vb
  name: StageDataInterface.StageConfigDataInterface
  nameWithType: StageDataInterface.StageConfigDataInterface
  fullName: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface
  type: Class
  source:
    remote:
      path: Public/Functor/Interfaces/StageDataInterface.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: StageConfigDataInterface
    path: ../Public/Functor/Interfaces/StageDataInterface.cs
    startLine: 403
  assemblies:
  - RGBLineCoreLib_ForEditor
  namespace: RGBLineCoreLib.Functor
  summary: 현재 StageData의 StageConfigData에 접근하기 위한 Interface
  example: []
  syntax:
    content: public static class StageDataInterface.StageConfigDataInterface
    content.vb: Public Module StageDataInterface.StageConfigDataInterface
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.GetStageConfigData
  commentId: M:RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.GetStageConfigData
  id: GetStageConfigData
  parent: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface
  langs:
  - csharp
  - vb
  name: GetStageConfigData()
  nameWithType: StageDataInterface.StageConfigDataInterface.GetStageConfigData()
  fullName: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.GetStageConfigData()
  type: Method
  source:
    remote:
      path: Public/Functor/Interfaces/StageDataInterface.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: GetStageConfigData
    path: ../Public/Functor/Interfaces/StageDataInterface.cs
    startLine: 409
  assemblies:
  - RGBLineCoreLib_ForEditor
  namespace: RGBLineCoreLib.Functor
  summary: 현재 StageData의 StageConfigData를 반환한다
  example: []
  syntax:
    content: public static StageData.StageConfigData GetStageConfigData()
    return:
      type: RGBLineCoreLib.Data.StageData.StageConfigData
    content.vb: Public Shared Function GetStageConfigData() As StageData.StageConfigData
  overload: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.GetStageConfigData*
- uid: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.SetStageConfigData(RGBLineCoreLib.Data.StageData.StageConfigData@)
  commentId: M:RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.SetStageConfigData(RGBLineCoreLib.Data.StageData.StageConfigData@)
  id: SetStageConfigData(RGBLineCoreLib.Data.StageData.StageConfigData@)
  parent: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface
  langs:
  - csharp
  - vb
  name: SetStageConfigData(in StageConfigData)
  nameWithType: StageDataInterface.StageConfigDataInterface.SetStageConfigData(in StageData.StageConfigData)
  fullName: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.SetStageConfigData(in RGBLineCoreLib.Data.StageData.StageConfigData)
  type: Method
  source:
    remote:
      path: Public/Functor/Interfaces/StageDataInterface.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: SetStageConfigData
    path: ../Public/Functor/Interfaces/StageDataInterface.cs
    startLine: 417
  assemblies:
  - RGBLineCoreLib_ForEditor
  namespace: RGBLineCoreLib.Functor
  syntax:
    content: public static void SetStageConfigData(in StageData.StageConfigData targetStageConfigData)
    parameters:
    - id: targetStageConfigData
      type: RGBLineCoreLib.Data.StageData.StageConfigData
    content.vb: Public Shared Sub SetStageConfigData(targetStageConfigData As StageData.StageConfigData)
  overload: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.SetStageConfigData*
  nameWithType.vb: StageDataInterface.StageConfigDataInterface.SetStageConfigData(StageData.StageConfigData)
  fullName.vb: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.SetStageConfigData(RGBLineCoreLib.Data.StageData.StageConfigData)
  name.vb: SetStageConfigData(StageConfigData)
references:
- uid: RGBLineCoreLib.Functor
  commentId: N:RGBLineCoreLib.Functor
  href: RGBLineCoreLib.html
  name: RGBLineCoreLib.Functor
  nameWithType: RGBLineCoreLib.Functor
  fullName: RGBLineCoreLib.Functor
  spec.csharp:
  - uid: RGBLineCoreLib
    name: RGBLineCoreLib
    href: RGBLineCoreLib.html
  - name: .
  - uid: RGBLineCoreLib.Functor
    name: Functor
    href: RGBLineCoreLib.Functor.html
  spec.vb:
  - uid: RGBLineCoreLib
    name: RGBLineCoreLib
    href: RGBLineCoreLib.html
  - name: .
  - uid: RGBLineCoreLib.Functor
    name: Functor
    href: RGBLineCoreLib.Functor.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.GetStageConfigData*
  commentId: Overload:RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.GetStageConfigData
  href: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.html#RGBLineCoreLib_Functor_StageDataInterface_StageConfigDataInterface_GetStageConfigData
  name: GetStageConfigData
  nameWithType: StageDataInterface.StageConfigDataInterface.GetStageConfigData
  fullName: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.GetStageConfigData
- uid: RGBLineCoreLib.Data.StageData.StageConfigData
  commentId: T:RGBLineCoreLib.Data.StageData.StageConfigData
  parent: RGBLineCoreLib.Data
  href: RGBLineCoreLib.Data.StageData.html
  name: StageData.StageConfigData
  nameWithType: StageData.StageConfigData
  fullName: RGBLineCoreLib.Data.StageData.StageConfigData
  spec.csharp:
  - uid: RGBLineCoreLib.Data.StageData
    name: StageData
    href: RGBLineCoreLib.Data.StageData.html
  - name: .
  - uid: RGBLineCoreLib.Data.StageData.StageConfigData
    name: StageConfigData
    href: RGBLineCoreLib.Data.StageData.StageConfigData.html
  spec.vb:
  - uid: RGBLineCoreLib.Data.StageData
    name: StageData
    href: RGBLineCoreLib.Data.StageData.html
  - name: .
  - uid: RGBLineCoreLib.Data.StageData.StageConfigData
    name: StageConfigData
    href: RGBLineCoreLib.Data.StageData.StageConfigData.html
- uid: RGBLineCoreLib.Data
  commentId: N:RGBLineCoreLib.Data
  href: RGBLineCoreLib.html
  name: RGBLineCoreLib.Data
  nameWithType: RGBLineCoreLib.Data
  fullName: RGBLineCoreLib.Data
  spec.csharp:
  - uid: RGBLineCoreLib
    name: RGBLineCoreLib
    href: RGBLineCoreLib.html
  - name: .
  - uid: RGBLineCoreLib.Data
    name: Data
    href: RGBLineCoreLib.Data.html
  spec.vb:
  - uid: RGBLineCoreLib
    name: RGBLineCoreLib
    href: RGBLineCoreLib.html
  - name: .
  - uid: RGBLineCoreLib.Data
    name: Data
    href: RGBLineCoreLib.Data.html
- uid: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.SetStageConfigData*
  commentId: Overload:RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.SetStageConfigData
  href: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.html#RGBLineCoreLib_Functor_StageDataInterface_StageConfigDataInterface_SetStageConfigData_RGBLineCoreLib_Data_StageData_StageConfigData__
  name: SetStageConfigData
  nameWithType: StageDataInterface.StageConfigDataInterface.SetStageConfigData
  fullName: RGBLineCoreLib.Functor.StageDataInterface.StageConfigDataInterface.SetStageConfigData
