### YamlMime:ManagedReference
items:
- uid: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  commentId: T:RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  id: GameConfigData.MaxFrameRate
  parent: RGBLineCoreLib.Data
  children:
  - RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_120
  - RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_30
  - RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_60
  - RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_90
  langs:
  - csharp
  - vb
  name: GameConfigData.MaxFrameRate
  nameWithType: GameConfigData.MaxFrameRate
  fullName: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  type: Enum
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: MaxFrameRate
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 14
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  summary: 지원하는 FPS 빈도를 지정한다
  example: []
  syntax:
    content: 'public enum GameConfigData.MaxFrameRate : byte'
    content.vb: Public Enum GameConfigData.MaxFrameRate As Byte
- uid: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_30
  commentId: F:RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_30
  id: Frame_30
  parent: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  langs:
  - csharp
  - vb
  name: Frame_30
  nameWithType: GameConfigData.MaxFrameRate.Frame_30
  fullName: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_30
  type: Field
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: Frame_30
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 16
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  syntax:
    content: Frame_30 = 0
    return:
      type: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
- uid: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_60
  commentId: F:RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_60
  id: Frame_60
  parent: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  langs:
  - csharp
  - vb
  name: Frame_60
  nameWithType: GameConfigData.MaxFrameRate.Frame_60
  fullName: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_60
  type: Field
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: Frame_60
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 17
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  syntax:
    content: Frame_60 = 1
    return:
      type: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
- uid: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_90
  commentId: F:RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_90
  id: Frame_90
  parent: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  langs:
  - csharp
  - vb
  name: Frame_90
  nameWithType: GameConfigData.MaxFrameRate.Frame_90
  fullName: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_90
  type: Field
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: Frame_90
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 18
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  syntax:
    content: Frame_90 = 2
    return:
      type: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
- uid: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_120
  commentId: F:RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_120
  id: Frame_120
  parent: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  langs:
  - csharp
  - vb
  name: Frame_120
  nameWithType: GameConfigData.MaxFrameRate.Frame_120
  fullName: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.Frame_120
  type: Field
  source:
    remote:
      path: Public/Data/Configs/GameConfigData.cs
      branch: master
      repo: https://github.com/RGB-Line/RGBLineCoreLib.git
    id: Frame_120
    path: ../Public/Data/Configs/GameConfigData.cs
    startLine: 19
  assemblies:
  - RGBLineCoreLib
  namespace: RGBLineCoreLib.Data
  syntax:
    content: Frame_120 = 3
    return:
      type: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
references:
- uid: RGBLineCoreLib.Data
  commentId: N:RGBLineCoreLib.Data
  href: RGBLineCoreLib.html
  name: RGBLineCoreLib.Data
  nameWithType: RGBLineCoreLib.Data
  fullName: RGBLineCoreLib.Data
  spec.csharp:
  - uid: RGBLineCoreLib
    name: RGBLineCoreLib
    href: RGBLineCoreLib.html
  - name: .
  - uid: RGBLineCoreLib.Data
    name: Data
    href: RGBLineCoreLib.Data.html
  spec.vb:
  - uid: RGBLineCoreLib
    name: RGBLineCoreLib
    href: RGBLineCoreLib.html
  - name: .
  - uid: RGBLineCoreLib.Data
    name: Data
    href: RGBLineCoreLib.Data.html
- uid: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  commentId: T:RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  parent: RGBLineCoreLib.Data
  href: RGBLineCoreLib.Data.GameConfigData.html
  name: GameConfigData.MaxFrameRate
  nameWithType: GameConfigData.MaxFrameRate
  fullName: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
  spec.csharp:
  - uid: RGBLineCoreLib.Data.GameConfigData
    name: GameConfigData
    href: RGBLineCoreLib.Data.GameConfigData.html
  - name: .
  - uid: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
    name: MaxFrameRate
    href: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.html
  spec.vb:
  - uid: RGBLineCoreLib.Data.GameConfigData
    name: GameConfigData
    href: RGBLineCoreLib.Data.GameConfigData.html
  - name: .
  - uid: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate
    name: MaxFrameRate
    href: RGBLineCoreLib.Data.GameConfigData.MaxFrameRate.html
